[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667EEA"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F5FF"
textColor = "#2D3436"
font = "sans serif"
